#!/usr/bin/env bash

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
definition="$REPO_ROOT/LabConfig/lab.json"

printf '# Canonical inventory summary\n\n'
# shellcheck disable=SC2016
printf '> Generated by `Tools/Generate-LabDocumentation.sh`. Edit `LabConfig/lab.json`, not this file.\n\n'
printf '| VM ID | Name | Role | OS | vCPU | RAM MB | Storage GB | Address | VLAN |\n'
printf '|---:|---|---|---|---:|---:|---:|---|---:|\n'
jq -r '
  . as $lab |
  .virtualMachines[] |
  [
    .id,
    .name,
    .role,
    .os,
    .cores,
    .memoryMB,
    (.diskGB + ((.dataDisks // []) | map(.sizeGB) | add // 0)),
    .nics[0].ipAddress,
    $lab.networks[.nics[0].network].vlanId
  ] |
  "| \(.[0]) | \(.[1]) | \(.[2]) | \(.[3]) | \(.[4]) | \(.[5]) | \(.[6]) | `\(.[7])` | \(.[8]) |"
' "$definition"

jq -r '
  "\n**Totals:** \(.virtualMachines | length) VMs, \([.virtualMachines[] | select(.os == "server-2025")] | length) servers, \([.virtualMachines[] | select(.os == "windows-11")] | length) client, \([.virtualMachines[].cores] | add) vCPU, \([.virtualMachines[].memoryMB] | add) MB RAM, \([.virtualMachines[] | .diskGB + ((.dataDisks // []) | map(.sizeGB) | add // 0)] | add) GB thin-provisioned storage."
' "$definition"

printf '\n## Networks\n\n'
printf '| Network | VLAN | CIDR | Gateway | DNS |\n'
printf '|---|---:|---|---|---|\n'
jq -r '.networks | to_entries[] | "| \(.key) | \(.value.vlanId) | `\(.value.cidr)` | `\(.value.gateway)` | \(.value.dnsServers | map("`" + . + "`") | join(", ")) |"' "$definition"
