#!/usr/bin/env bash

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

printf '# Canonical inventory summary\n\n'
# Backticks are intentional Markdown, not shell substitution.
# shellcheck disable=SC2016
printf '> Generated by `Tools/Generate-LabDocumentation.sh`. Edit the JSON definitions, not this file.\n\n'
printf '| Demo | Profile | Domain | VMs | Servers | Clients | vCPU | RAM MB | Disk GB |\n'
printf '|---|---|---|---:|---:|---:|---:|---:|---:|\n'
for demo in asgard olympus; do
  definition="$REPO_ROOT/LabConfig/demos/$demo.json"
  for profile in smoke core full; do
    jq -r --arg profile "$profile" '
      [.virtualMachines[] | select(.profiles | index($profile))] as $selected |
      [.displayName, $profile, .domain.dnsName, ($selected | length), ([$selected[] | select(.role != "client" and .role != "aiml-client")] | length), ([$selected[] | select(.role == "client" or .role == "aiml-client")] | length), ([$selected[] | (.profileResourceOverrides[$profile].cores // .cores)] | add), ([$selected[] | (.profileResourceOverrides[$profile].memoryMB // .memoryMB)] | add), ([$selected[] | ((.profileResourceOverrides[$profile].diskGB // .diskGB) + ((.profileDataDiskOverrides[$profile] // .dataDisks // []) | map(.sizeGB) | add // 0))] | add)] |
      "| \(.[0]) | \(.[1]) | `\(.[2])` | \(.[3]) | \(.[4]) | \(.[5]) | \(.[6]) | \(.[7]) | \(.[8]) |"
    ' "$definition"
  done
done

for demo in asgard olympus; do
  definition="$REPO_ROOT/LabConfig/demos/$demo.json"
  display_name="$(jq -r '.displayName' "$definition")"
  servers="$(jq -r '[.virtualMachines[] | select(.role != "client" and .role != "aiml-client") | "\(.name) (\(.role))"] | join(", ")' "$definition")"
  clients="$(jq -r '[.virtualMachines[] | select(.role == "client" or .role == "aiml-client") | .name] | join(", ")' "$definition")"
  printf '\n## %s\n\n' "$display_name"
  printf '**Servers:** %s\n\n' "$servers"
  printf '**Full-profile clients (25):** %s\n' "$clients"
done
